#!/bin/bash -l
#PBS -N Netcdf_SnowModel_Processing
#PBS -A P48500028
#PBS -l select=1:ncpus=1:mpiprocs=1:ompthreads=1:mem=200GB
#PBS -l walltime=4:00:00
#PBS -q casper
#PBS -j oe

### Set TMPDIR as recommended
export TMPDIR=/glade/scratch/$USER/temp_serial
mkdir -p $TMPDIR


###module swap
source /glade/u/home/rossamower/work/miniconda3/etc/profile.d/conda.sh
conda activate geospatial

### Run the executable
python3 main.py
